### ISSUE TITLE
Simulator not working

### ISSUE THREAD

**Issue by dantudose** [ellisgl/SAP-1-CPU#2]
The simulator seems to not work anymore. Tried to program the first instruction in the sample program LDA 1010 but the LEDs don't light up and when I hit Load, the instruction is not visible in the RAM memory map below (at Debug). I'm using the gui at http://ellisgl.github.io/SAP-1-CPU/

**Comment by ellisgl** [comment]
Strange - let me get that fixed.

**Comment by ellisgl** [comment]
Fixed.
